plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

group = project.mod_group_id
version = project.mod_version

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = uri('https://api.modrinth.com/maven')
            }
        }
        filter { includeGroup 'maven.modrinth' }
    }
}

neoForge {
    version = project.neo_version
    parchment {
        minecraftVersion = '1.21.1'
        mappingsVersion = '2024.11.17'
    }
    runs {
        client { client() }
        server { server() }
        data { data() }
    }
    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "org.appliedenergistics:appliedenergistics2:${project.ae2_version}"
    implementation "maven.modrinth:sophisticated-core:${project.sophisticated_core_version}"
    implementation "maven.modrinth:sophisticated-backpacks:${project.sophisticated_backpacks_version}"
    implementation "maven.modrinth:sophisticated-storage:${project.sophisticated_storage_version}"
}

var replaceProperties = [
    minecraft_version      : minecraft_version,
    minecraft_version_range: minecraft_version_range,
    neo_version            : neo_version,
    neo_version_range      : neo_version_range,
    loader_version_range   : loader_version_range,
    mod_id                 : mod_id,
    mod_name               : mod_name,
    mod_license            : mod_license,
    mod_version            : mod_version,
    mod_authors            : mod_authors,
    mod_description        : mod_description
]

processResources {
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

