modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mixins]]
config="sophisticated_ae_addons.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[19.2.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedcore"
type="required"
versionRange="[1.4.80,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
versionRange="[3.25.73,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedstorage"
type="optional"
versionRange="[1.5.83,)"
ordering="AFTER"
side="BOTH"
